apiVersion: v1
kind: Service
metadata:
    name: svc-microservicessoaclient
    labels:
        product: microservicessoaclient
spec:
    selector:
        app: app-microservicessoaclient
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dep-microservicessoaclient
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: app-microservicessoaclient
        spec:
            containers:
            - image: psreleasedemoerick.azurecr.io/microservicessoaclient:__Build.BuildId__
              imagePullPolicy: IfNotPresent
              name: microservicessoaclient
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: regsecret